repos:
- repo: local
  hooks:
  - id: lint-code
    name: Dart Lint code
    always_run: true
    entry: dart
    args: ["fix", "lib", "--apply"]
    language: system
    types: [bash]
  - id: format-code
    name: Flutter format code
    always_run: true
    entry: dart
    args: ["format", "--fix", "."]
    language: system
    types: [bash]
  - id: test-code
    name: Flutter test code
    always_run: true
    entry: flutter
    args: ["test"]
    language: system
    types: [bash]
  - id: static-code-analysis
    name: Flutter analyze code
    always_run: true
    entry: flutter
    args: ["analyze"]
    language: system
    types: [bash]
