name: xid
description: |
  Xid is a globally unique id generator. Xids are small, fast to generate, sortable, 
  compact URL-safe string with no configuration or central generator server.
  
version: 1.2.1
repository: https://github.com/pitabwire/xid
environment:
  sdk: ^2.18.0

dev_dependencies:
  flutter_lints: ^2.0.2
  test: ^1.16.0

