# A CI configuration to write comments on PRs.

name: Comment on the pull request

on:
  workflow_run:
    workflows:
      - Publish
    types:
      - completed

jobs:
  upload:
    permissions:
      pull-requests: write
    uses: dart-lang/ecosystem/.github/workflows/post_summaries.yaml@main
