name: Test all code changes

on: [ push ]

jobs:

  build:
    strategy:
      matrix:
        dart_version: [ 2.14,2.15,2.16,2.17,2.18,2.19,3.0,3.1,3.2 ]
    runs-on: ubuntu-latest
    container:
      image: dart:${{ matrix.dart_version }}
    steps:
      - name: Checkout code for testing
        uses: actions/checkout@v4
      - name: Run all tests in project
        run: dart test test/
